services:
  builder:
    build: .
    container_name: blankon-builder
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - .:/build
      - build-workspace:/workspace
      - ${HOST_JAHITAN_PATH}:/jahitan
    env_file:
      - .env

volumes:
  build-workspace:
